// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAts3EGWRa46AnKXuKMyD2LFTarDYu8PJ4',
    appId: '1:384136070006:web:1996145989d72321fd7057',
    messagingSenderId: '384136070006',
    projectId: 'tnpsc-prepare-app-koilra-c9998',
    authDomain: 'tnpsc-prepare-app-koilra-c9998.firebaseapp.com',
    storageBucket: 'tnpsc-prepare-app-koilra-c9998.firebasestorage.app',
    measurementId: 'G-6RZKZXNP8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEhEZzEfhiQo4LhGdwDhJfIsv1Y4CjKDs',
    appId: '1:384136070006:android:44e37a92b196737dfd7057',
    messagingSenderId: '384136070006',
    projectId: 'tnpsc-prepare-app-koilra-c9998',
    storageBucket: 'tnpsc-prepare-app-koilra-c9998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54Sz8HC3YmVOjRS7EHO1YQwtCoGXnQfg',
    appId: '1:384136070006:ios:7a3506605efd3f9efd7057',
    messagingSenderId: '384136070006',
    projectId: 'tnpsc-prepare-app-koilra-c9998',
    storageBucket: 'tnpsc-prepare-app-koilra-c9998.firebasestorage.app',
    iosBundleId: 'com.tnpsc.groupbook.tnpscGroupBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54Sz8HC3YmVOjRS7EHO1YQwtCoGXnQfg',
    appId: '1:384136070006:ios:7a3506605efd3f9efd7057',
    messagingSenderId: '384136070006',
    projectId: 'tnpsc-prepare-app-koilra-c9998',
    storageBucket: 'tnpsc-prepare-app-koilra-c9998.firebasestorage.app',
    iosBundleId: 'com.tnpsc.groupbook.tnpscGroupBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAts3EGWRa46AnKXuKMyD2LFTarDYu8PJ4',
    appId: '1:384136070006:web:3f23a0f2d1288da0fd7057',
    messagingSenderId: '384136070006',
    projectId: 'tnpsc-prepare-app-koilra-c9998',
    authDomain: 'tnpsc-prepare-app-koilra-c9998.firebaseapp.com',
    storageBucket: 'tnpsc-prepare-app-koilra-c9998.firebasestorage.app',
    measurementId: 'G-P3J3JG1PK2',
  );

}