org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
kotlin.daemon.jvmargs=-Xmx2G
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
systemProp.java.net.preferIPv4Stack=true
android.r8.optimizedResourceShrinking=true
android.enableResourceOptimizations=true
android.enableR8.fullMode=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
