org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
kotlin.daemon.jvmargs=-Xmx2G
android.useAndroidX=true
systemProp.java.net.preferIPv4Stack=true
android.enableR8.fullMode=true
android.suppressUnsupportedCompileSdk=36
# android.defaults.buildfeatures.buildconfig=true
android.advanced.profiling=false
android.builtInKotlin=false
android.newDsl=false
