org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2G
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
systemProp.java.net.preferIPv4Stack=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=false
android.newDsl=false
